# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo03' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo03
  pod 'Moya', '~> 15.0'  
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'Moya/ReactiveSwift', '~> 15.0'

  target 'demo03Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo03UITests' do
    # Pods for testing
  end

end
